name: Java DfuSe

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-java@v1
        with:
          java-version: '8'

      - name: Test Compiler
        run: javac -version

      - name: Build
        working-directory: ./
        run: bash ./gradlew build

      - name: Upload JAR
        uses: actions/upload-artifact@v2
        with:
          name: dfu_java
          path: ./build/libs/dfu_java.jar

